# Default values for openldap.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: osixia/openldap
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "1.5.0"
initJob:
  image:
    repository: osixia/openldap
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "1.5.0"

imagePullSecrets: []

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  ldapPort: 389
  sslLdapPort: 636

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

# create some initial user data
initialData: []
# - |
#   dn: cn=Barbara Jensen,dc=example,dc=com
#   objectClass: person
#   cn: Barbara Jensen
#   cn: Babs Jensen
#   sn: Jensen
#   title: the world's most famous mythical manager
#   mail: bjensen@example.com
#   uid: bjensen

initialData:
- |
  dn: cn=Barbara Jensen,dc=example,dc=com
  objectClass: person
  cn: Barbara Jensen
  cn: Babs Jensen
  sn: Jensen
  title: the world's most famous mythical manager
  mail: bjensen@example.com
  uid: bjensen

env:
  LDAP_ORGANISATION: "Example Inc."
  LDAP_DOMAIN: "example.org"
  LDAP_BACKEND: "hdb"
  LDAP_TLS: "true"
  LDAP_TLS_ENFORCE: "false"
  LDAP_REMOVE_CONFIG_AFTER_SETUP: "true"

tls:
  enabled: false

persistence:
  enabled: false
  existingClaim: ""

logLevel: info
